// Single source of truth for the native <-> web bridge.
// Swift mirrors these types in EnjinKit/Sources/EnjinKit/Bridge; both sides
// test against the fixtures generated by scripts/gen-fixtures.ts.
import { z } from "zod";

export const PROTOCOL_VERSION = 1;

// ---------- shared models ----------

export const CardType = z.enum(["topic", "source", "image", "note"]);
export const CardState = z.enum(["stub", "filling", "filled", "error"]);

export const CardImageRef = z.object({
  fileId: z.string(),
  /** Natural pixel size, for fitting without distortion. */
  width: z.number().int().positive(),
  height: z.number().int().positive(),
});

/** One row of a figure: a step, an event, a bar, a part, a symbol. */
export const VisualItem = z.object({
  label: z.string(),
  /** A few words under the label (step detail, what a symbol means). */
  detail: z.string().optional(),
  /** Bars: the number. */
  value: z.number().optional(),
  /** Timeline: when ("1969", "4.6 bn years ago"). */
  tag: z.string().optional(),
});
export type VisualItem = z.infer<typeof VisualItem>;

export const VisualKind = z.enum(["flow", "cycle", "timeline", "bars", "parts", "stat", "formula", "code", "live", "graph", "table", "chart",
  "model3d", "diorama", "ui"]);

/** graph: a labelled relation between two nodes (by label). */
export const VisualLink = z.object({ from: z.string(), to: z.string(), label: z.string().optional() });
export type VisualLink = z.infer<typeof VisualLink>;

/** chart: one named series of [x, y] points. */
export const VisualSeries = z.object({ label: z.string(), points: z.array(z.tuple([z.number(), z.number()])) });
export type VisualSeries = z.infer<typeof VisualSeries>;
export type VisualKind = z.infer<typeof VisualKind>;

/**
 * A figure drawn on the card as canvas geometry (not a picture):
 * flow (steps →), cycle (steps in a loop), timeline (tag + label), bars
 * (label + value, `unit`), parts (`center` + labelled parts), stat (big
 * `value` + `unit`), formula (`text` + items as symbol legend), code (`text`),
 * live (`html`: a small interactive simulation or animated diorama, run in a
 * sandboxed iframe with no network; absent while it's still being written),
 * graph (items = nodes, `links` = labelled relations, laid out automatically),
 * table (`columns` + `rows` of cells), chart (`series` of points, `plot` line or
 * scatter, axis labels, optional log y). Skills (run by ENJIN's own runtimes in
 * a sandboxed frame, from a `spec`): model3d (parts, camera, motion), diorama
 * (depth layers of props, hotspots, optional generated backdrop = the card's
 * picture), ui (generative interactive UI: state + blocks).
 */
export const Visual = z.object({
  kind: VisualKind,
  items: z.array(VisualItem).optional(),
  center: z.string().optional(),
  value: z.string().optional(),
  unit: z.string().optional(),
  text: z.string().optional(),
  html: z.string().optional(),
  links: z.array(VisualLink).optional(),
  columns: z.array(z.string()).optional(),
  rows: z.array(z.array(z.string())).optional(),
  series: z.array(VisualSeries).optional(),
  plot: z.enum(["line", "scatter"]).optional(),
  xLabel: z.string().optional(),
  yLabel: z.string().optional(),
  logY: z.boolean().optional(),
  spec: z.record(z.string(), z.unknown()).optional(),
});
export type Visual = z.infer<typeof Visual>;

export const Card = z.object({
  id: z.string(),
  type: CardType,
  title: z.string(),
  summary: z.string(),
  state: CardState,
  /** Number of cards inside this card's portal (0 = never dived). */
  childCount: z.number().int().nonnegative(),
  image: CardImageRef.optional(),
  /** A picture is being looked for: reserve its space with a placeholder. */
  imagePending: z.boolean().optional(),
  /** A figure drawn on the card (cards with a figure have no picture). */
  visual: Visual.optional(),
});
export type Card = z.infer<typeof Card>;

export const Crumb = z.object({ portalId: z.string(), title: z.string() });

/** Excalidraw BinaryFileData, minus `created`. */
export const BridgeFile = z.object({ id: z.string(), mimeType: z.string(), dataURL: z.string() });
export type BridgeFile = z.infer<typeof BridgeFile>;

export const PortalScene = z.object({
  portalId: z.string(),
  title: z.string(),
  /** Root first, this portal last. */
  path: z.array(Crumb).min(1),
  cards: z.array(Card),
  /** Persisted Excalidraw elements; empty on first visit (web lays out cards). */
  elements: z.array(z.record(z.string(), z.unknown())),
  /** Images used by this portal's cards. */
  files: z.array(BridgeFile).optional(),
  /** The card this portal is inside: its picture as a banner, its summary under the title. */
  hero: CardImageRef.optional(),
  subtitle: z.string().optional(),
});
export type PortalScene = z.infer<typeof PortalScene>;

export const Transition = z.enum(["dive", "exit", "jump"]);

export const CardOp = z.discriminatedUnion("op", [
  z.object({ op: z.literal("upsert"), card: Card }),
  z.object({ op: z.literal("delete"), cardId: z.string() }),
]);
export type CardOp = z.infer<typeof CardOp>;

export const PlacedCard = z.object({ cardId: z.string(), x: z.number(), y: z.number(), width: z.number(), height: z.number() });

// ---------- methods ----------
// Every method has params and a result schema. Notifications return null.

const Null = z.null();

export const nativeToWeb = {
  "portal.load": {
    params: z.object({
      scene: PortalScene,
      transition: Transition,
      /** Card to frame after load (exit: the card we came from). */
      focusCardId: z.string().optional(),
    }),
    result: Null,
  },
  "ink.lock": {
    params: z.object({ locked: z.boolean() }),
    result: Null,
  },
  "ink.commit": {
    params: z.object({
      strokeId: z.string(),
      tool: z.enum(["pen", "highlighter"]),
      color: z.string(),
      width: z.number().positive(),
      /** WebView-local points in CSS px: [x, y] pairs. */
      points: z.array(z.tuple([z.number(), z.number()])).min(1),
      /** 0..1, same length as points. */
      pressures: z.array(z.number().min(0).max(1)),
    }),
    /** Resolves after the element has been rendered. */
    result: z.object({ strokeId: z.string(), elementId: z.string() }),
  },
  "canvas.applyOps": {
    params: z.object({
      /** Ops for a portal that isn't on screen are ignored (native already stored them). */
      portalId: z.string(),
      ops: z.array(CardOp),
    }),
    /** Where each upserted card ended up (empty if the portal isn't current). */
    result: z.object({ placed: z.array(PlacedCard) }),
  },
  "canvas.setHeader": {
    params: z.object({ portalId: z.string(), title: z.string(), subtitle: z.string().optional(), hero: CardImageRef.optional() }),
    result: Null,
  },
  "canvas.setBusy": {
    /** Shown in an empty portal while Enjin fills it; omitted/undefined hides it. */
    params: z.object({ portalId: z.string(), message: z.string().optional() }),
    result: Null,
  },
  "canvas.setInsets": {
    /** Screen space (CSS px) covered by native chrome; content is framed clear of it. */
    params: z.object({ top: z.number(), left: z.number(), bottom: z.number(), right: z.number() }),
    result: Null,
  },
  "canvas.setTool": {
    /** The native tool rail picked a tool. Pencil goes to native ink only for draw/highlight. */
    params: z.object({
      tool: z.enum(["selection", "freedraw", "highlighter", "text", "rectangle", "ellipse", "arrow", "eraser"]),
      color: z.string(),
    }),
    result: Null,
  },
  "canvas.history": {
    params: z.object({ action: z.enum(["undo", "redo"]) }),
    result: Null,
  },
  "canvas.setLanguage": {
    params: z.object({ language: z.enum(["en", "da"]) }),
    result: Null,
  },
  "canvas.addFiles": {
    params: z.object({ files: z.array(BridgeFile) }),
    result: Null,
  },
  "canvas.frame": {
    /** Kid asked to go to a card (e.g. tapped a suggestion): ease the camera onto it. */
    params: z.object({ cardId: z.string() }),
    result: z.object({ framed: z.boolean() }),
  },
  "canvas.flash": {
    params: z.object({ cardId: z.string() }),
    result: Null,
  },
} as const;

export const webToNative = {
  "canvas.ready": {
    params: z.object({ protocolVersion: z.number().int(), excalidrawVersion: z.string() }),
    result: z.object({ accepted: z.boolean(), reason: z.string().optional() }),
  },
  "canvas.changed": {
    params: z.object({
      portalId: z.string(),
      elements: z.array(z.record(z.string(), z.unknown())),
    }),
    result: Null,
  },
  "focus.changed": {
    params: z.object({
      portalId: z.string(),
      cardId: z.string().nullable(),
      zoom: z.number().positive(),
      visibleCardIds: z.array(z.string()),
    }),
    result: Null,
  },
  "card.open": {
    /** Kid tapped the card's Open action: show its detail sheet. */
    params: z.object({ cardId: z.string() }),
    result: Null,
  },
  "card.visualize": {
    /** Explorer tapped Visualize: Enjin turns the card's idea into a figure or live model beside it. */
    params: z.object({ cardId: z.string() }),
    result: Null,
  },
  "media.stylize": {
    /** An image arrived on the canvas without native (e.g. pasted): give it the ENJIN look. */
    params: z.object({ dataURL: z.string(), mimeType: z.string() }),
    result: z.object({ dataURL: z.string(), mimeType: z.string() }),
  },
  "selection.changed": {
    /** Cards whose frame is selected (a card is selected as a group). */
    params: z.object({ portalId: z.string(), cardIds: z.array(z.string()) }),
    result: Null,
  },
  "portal.enter": {
    params: z.object({ portalId: z.string(), cardId: z.string() }),
    /** null = cannot dive (e.g. not a topic card). */
    result: PortalScene.nullable(),
  },
  "portal.exit": {
    params: z.object({ portalId: z.string() }),
    /** null = already at root. */
    result: z.object({ scene: PortalScene, focusCardId: z.string() }).nullable(),
  },
  "log.event": {
    params: z.object({
      level: z.enum(["debug", "info", "warn", "error"]),
      message: z.string(),
      data: z.record(z.string(), z.unknown()).optional(),
    }),
    result: Null,
  },
} as const;

export type NativeToWeb = typeof nativeToWeb;
export type WebToNative = typeof webToNative;
export type Params<M extends Record<string, { params: z.ZodTypeAny }>, K extends keyof M> = z.infer<M[K]["params"]>;
export type Result<M extends Record<string, { result: z.ZodTypeAny }>, K extends keyof M> = z.infer<M[K]["result"]>;

// ---------- envelope ----------

export const Request = z.object({
  v: z.number().int(),
  id: z.string(),
  method: z.string(),
  params: z.unknown(),
});
export type Request = z.infer<typeof Request>;

export const ErrorCode = {
  versionMismatch: -32000,
  methodNotFound: -32601,
  invalidParams: -32602,
  internal: -32603,
} as const;

export const Response = z.union([
  z.object({ v: z.number().int(), id: z.string(), result: z.unknown() }),
  z.object({
    v: z.number().int(),
    id: z.string(),
    error: z.object({ code: z.number().int(), message: z.string() }),
  }),
]);
export type Response = z.infer<typeof Response>;
