// Single source of truth for the native <-> web bridge.
// Swift mirrors these types in EnjinKit/Sources/EnjinKit/Bridge; both sides
// test against the fixtures generated by scripts/gen-fixtures.ts.
import { z } from "zod";

export const PROTOCOL_VERSION = 1;

// ---------- shared models ----------

export const CardType = z.enum(["topic", "source", "image", "note"]);
export const CardState = z.enum(["stub", "filling", "filled", "error"]);

export const Card = z.object({
  id: z.string(),
  type: CardType,
  title: z.string(),
  summary: z.string(),
  state: CardState,
  /** Number of cards inside this card's portal (0 = never dived). */
  childCount: z.number().int().nonnegative(),
});
export type Card = z.infer<typeof Card>;

export const Crumb = z.object({ portalId: z.string(), title: z.string() });

export const PortalScene = z.object({
  portalId: z.string(),
  title: z.string(),
  /** Root first, this portal last. */
  path: z.array(Crumb).min(1),
  cards: z.array(Card),
  /** Persisted Excalidraw elements; empty on first visit (web lays out cards). */
  elements: z.array(z.record(z.string(), z.unknown())),
});
export type PortalScene = z.infer<typeof PortalScene>;

export const Transition = z.enum(["dive", "exit", "jump"]);

export const CardOp = z.discriminatedUnion("op", [
  z.object({ op: z.literal("upsert"), card: Card }),
  z.object({ op: z.literal("delete"), cardId: z.string() }),
]);
export type CardOp = z.infer<typeof CardOp>;

export const PlacedCard = z.object({ cardId: z.string(), x: z.number(), y: z.number(), width: z.number(), height: z.number() });

// ---------- methods ----------
// Every method has params and a result schema. Notifications return null.

const Null = z.null();

export const nativeToWeb = {
  "portal.load": {
    params: z.object({
      scene: PortalScene,
      transition: Transition,
      /** Card to frame after load (exit: the card we came from). */
      focusCardId: z.string().optional(),
    }),
    result: Null,
  },
  "ink.lock": {
    params: z.object({ locked: z.boolean() }),
    result: Null,
  },
  "ink.commit": {
    params: z.object({
      strokeId: z.string(),
      tool: z.enum(["pen", "highlighter"]),
      color: z.string(),
      width: z.number().positive(),
      /** WebView-local points in CSS px: [x, y] pairs. */
      points: z.array(z.tuple([z.number(), z.number()])).min(1),
      /** 0..1, same length as points. */
      pressures: z.array(z.number().min(0).max(1)),
    }),
    /** Resolves after the element has been rendered. */
    result: z.object({ strokeId: z.string(), elementId: z.string() }),
  },
  "canvas.applyOps": {
    params: z.object({
      /** Ops for a portal that isn't on screen are ignored (native already stored them). */
      portalId: z.string(),
      ops: z.array(CardOp),
    }),
    /** Where each upserted card ended up (empty if the portal isn't current). */
    result: z.object({ placed: z.array(PlacedCard) }),
  },
  "canvas.flash": {
    params: z.object({ cardId: z.string() }),
    result: Null,
  },
} as const;

export const webToNative = {
  "canvas.ready": {
    params: z.object({ protocolVersion: z.number().int(), excalidrawVersion: z.string() }),
    result: z.object({ accepted: z.boolean(), reason: z.string().optional() }),
  },
  "canvas.changed": {
    params: z.object({
      portalId: z.string(),
      elements: z.array(z.record(z.string(), z.unknown())),
    }),
    result: Null,
  },
  "focus.changed": {
    params: z.object({
      portalId: z.string(),
      cardId: z.string().nullable(),
      zoom: z.number().positive(),
      visibleCardIds: z.array(z.string()),
    }),
    result: Null,
  },
  "selection.changed": {
    /** Cards whose frame is selected (a card is selected as a group). */
    params: z.object({ portalId: z.string(), cardIds: z.array(z.string()) }),
    result: Null,
  },
  "portal.enter": {
    params: z.object({ portalId: z.string(), cardId: z.string() }),
    /** null = cannot dive (e.g. not a topic card). */
    result: PortalScene.nullable(),
  },
  "portal.exit": {
    params: z.object({ portalId: z.string() }),
    /** null = already at root. */
    result: z.object({ scene: PortalScene, focusCardId: z.string() }).nullable(),
  },
  "log.event": {
    params: z.object({
      level: z.enum(["debug", "info", "warn", "error"]),
      message: z.string(),
      data: z.record(z.string(), z.unknown()).optional(),
    }),
    result: Null,
  },
} as const;

export type NativeToWeb = typeof nativeToWeb;
export type WebToNative = typeof webToNative;
export type Params<M extends Record<string, { params: z.ZodTypeAny }>, K extends keyof M> = z.infer<M[K]["params"]>;
export type Result<M extends Record<string, { result: z.ZodTypeAny }>, K extends keyof M> = z.infer<M[K]["result"]>;

// ---------- envelope ----------

export const Request = z.object({
  v: z.number().int(),
  id: z.string(),
  method: z.string(),
  params: z.unknown(),
});
export type Request = z.infer<typeof Request>;

export const ErrorCode = {
  versionMismatch: -32000,
  methodNotFound: -32601,
  invalidParams: -32602,
  internal: -32603,
} as const;

export const Response = z.union([
  z.object({ v: z.number().int(), id: z.string(), result: z.unknown() }),
  z.object({
    v: z.number().int(),
    id: z.string(),
    error: z.object({ code: z.number().int(), message: z.string() }),
  }),
]);
export type Response = z.infer<typeof Response>;
